spring:
  application:
    name: Active Users Display
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
      timeout: 3000

management:
  server:
    port: 8081 # Expose metrics on a different port
  endpoints:
    web:
      exposure:
        include: "*"


